### ISSUE TITLE
Ansible is not creating drives correctly

### ISSUE THREAD

**Issue by thexder1** [GoogleCloudPlatform/magic-modules#3724]
I first noticed this on Friday, June 26th when specifying a source_snapshot in Ansible playbook yaml file blank drives are being created. I can manually create drives with the same snapshots without issue and Ansible was creating them fine before with the same playbook and same Ansible version. Below is a snippet of a drive to be created.
``` 
- name: Create binlog disk
      gcp_compute_disk:
        name: gce-db-test-binlog
        size_gb: 2048
        zone: "{{ zone }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        scopes:
          - https://www.googleapis.com/auth/compute
        source_snapshot:
          selfLink: "https://www.googleapis.com/compute/v1/projects/{{ gcp_project }}/global/snapshots/db1-binlog-snap-{{ snapshot_timestamp }}"
        type: "pd-ssd"
```
